apiVersion: v1
kind: Secret
metadata:
  name: {{ include "protoforge.fullname" . }}-db-secret
  labels:
    {{- include "protoforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.username | quote }}
  password: {{ .Values.postgresql.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "protoforge.fullname" . }}-jwt-secret
  labels:
    {{- include "protoforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.jwtSecret | quote }}
